from app.models import db, Item, environment, SCHEMA


# Adds a handful of items, you can add other items here if you want
def seed_items():
    item1 = Item(
      name="Women's Lounge Fleece Sweatshirt", category='Clothing, Shoes & Accessories', description='Take your loungewear to the next level with this Lounge Fleece Sweatshirt from A New Day™. The solid-color fleece sweatshirt is made with a midweight cotton blend that provides warm layering. With a fun graphic on the front, as well as ribbed and striped edges on the crewneck, wrists and hemline, this long-sleeve pullover is tailored in a regular fit that hits below the waist for comfortable wear. Wear it with jeans, over your favorite athleisure ensemble or with matching shorts.', price=29.95, image_url='https://target.scene7.com/is/image/Target/GUEST_f62bbea5-12b8-4965-978b-0b7a97b61b04?wid=325&hei=325&qlt=80&fmt=pjpeg', in_stock=True
    )
    item2 = Item(
      name="Women's Long Sleeve T-Shirt", category='Clothing, Shoes & Accessories', description='Give a timeless upgrade to your casualwear with this Long-Sleeve T-Shirt from A New Day™. This pullover tee features a horizontal striped pattern and a tiny embroidered motif on the chest for a stylish look. Crafted from a soft fabric blend, this striped T-shirt is tailored in a classic fit that hits below the waist to keep you comfortable no matter what that day has in store.', price=19.95, image_url='https://target.scene7.com/is/image/Target/GUEST_08fb79a4-bb8c-4806-a6f4-74f7a7225c98?wid=325&hei=325&qlt=80&fmt=pjpeg', in_stock=True
    )
    item3 = Item(
      name="Men's Relaxed Fit Crew Neck Pullover Sweatshirt", category='Clothing, Shoes & Accessories', description='Spruce up your cool-weather outerwear with this Relaxed-Fit Crewneck Pullover Sweatshirt from Goodfellow & Co™. The solid-color sweatshirt is made from a heavyweight cotton blend that provides a warm layer, and it can be dressed up or down to fit a range of occasions. With a tiny graphic on the chest, as well as ribbed and striped edges on the crewneck, wrists and hemline, this long-sleeve pullover is tailored in a relaxed fit that hits at the hip for comfortable wear.', price=29.95, image_url='https://target.scene7.com/is/image/Target/GUEST_d519fa7d-43c8-4273-93dd-f64e4d559e1a?wid=325&hei=325&qlt=80&fmt=pjpeg', in_stock=True
    )
    item4 = Item(
      name="Men's Classic Fit Scoop Neck Long Sleeve T-Shirt", category='Clothing, Shoes & Accessories', description='Give a timeless upgrade to your casualwear with this Classic-Fit Scoop-Neck Long-Sleeve T-Shirt from Goodfellow & Co™. This pullover tee features a horizontal striped pattern and a chest patch pocket with an embroidered heart motif for a stylish look. Crafted from a soft fabric blend, this striped T-shirt is tailored in a classic fit that hits below the waist to keep you comfortable no matter what that day has in store.', price=24.95, image_url='https://target.scene7.com/is/image/Target/GUEST_0e23578d-19fe-4fa0-80e7-fcf0e8f1c0e3?wid=325&hei=325&qlt=80&fmt=pjpeg', in_stock=True
    )
    item5 = Item(
      name="Women's Full-Zip Jacket", category='Clothing, Shoes & Accessories', description='Stay warm on chilly days with this full-zip jacket made from cozy, heavyweight textured fabric. Front pockets provide a place to keep small essentials contained when you’re on the move, while the front full-length zipper allows for easy layering with all your favorite cool-weather basics. The at-hip length and adjustable hem with toggles round out the sporty look.', price=74.95, image_url='https://target.scene7.com/is/image/Target/GUEST_8b812859-2bed-4b96-93c9-597871e9af36?wid=325&hei=325&qlt=80&fmt=pjpeg', in_stock=True
    )
    item6 = Item(
      name="Men's Lightweight Tricot Jacket", category='Clothing, Shoes & Accessories', description='Solid-color tricot jacket with high-low hem makes a stylish addition to your activewear collection. The quick-dry, moisture-wicking fabric with four-way stretch helps keep you comfy throughout your activities. With the front full-length zipper, the jacket can be worn either closed or open.', price=84.95, image_url='https://target.scene7.com/is/image/Target/GUEST_613d57d0-b0d6-4077-b03d-e1fcb5ad1074?wid=325&hei=325&qlt=80&fmt=pjpeg', in_stock=True
    )
    item7 = Item(
      name="Men's Short Sleeve T-Shirt", category='Clothing, Shoes & Accessories', description='Solid-color T-shirt with zippered chest pocket adds cool style to your activewear collection. The moisture-wicking, midweight fabric helps keep you comfy throughout your activities. With a below-waist length, the crewneck tee allows for easy pairing with a variety of bottoms.', price=24.95, image_url='https://target.scene7.com/is/image/Target/GUEST_6a3dd892-aada-433f-9f2b-2a916ed27970?wid=325&hei=325&qlt=80&fmt=pjpeg', in_stock=True
    )
    item8 = Item(
      name="Men's Cotton Fleece Hooded Sweatshirt", category='Clothing, Shoes & Accessories', description='Solid-color sweatshirt in midweight fleece fabric with long sleeves, ribbed edges and a pullover design. The front kangaroo pocket and a drawstring hood round out the piece with even more coverage, warmth and customization.', price=34.95, image_url='https://target.scene7.com/is/image/Target/GUEST_b82dbd35-715f-483e-bf19-6b0468beab01?wid=325&hei=325&qlt=80&fmt=pjpeg', in_stock=True
    )
    item9 = Item(
      name="Women's Plus Size Ultra Value French Terry Hooded Sweatshirt", category='Clothing, Shoes & Accessories', description='French terry pullover sweatshirt that stretches and moves with you, thanks to the midweight cotton construction with added spandex. Thumbholes on the long sleeves keep them in place, and the attached hood and hand-warming front kangaroo pocket lend an additional layer of comfort. The regular fit and at-hip length allow it to be paired with cozy base layers.', price=34.95, image_url='https://target.scene7.com/is/image/Target/GUEST_5a301516-bdfc-4528-b89c-c39153d6185c?wid=325&hei=325&qlt=80&fmt=pjpeg', in_stock=True
    )
    item10 = Item(
      name="Women's Ribbed Fleece Cropped Hooded Sweatshirt", category='Clothing, Shoes & Accessories', description='This ribbed fleece cropped hooded sweatshirt is a cozy must-have for cooler weather. Soft midweight fabric with stretch offers warmth and comfortable wear, while thumbholes on each sleeve offer extra protection. A zip closure, cropped length and relaxed fit round out the stylish design.', price=34.95, image_url='https://target.scene7.com/is/image/Target/GUEST_3b0d03b9-d552-4ba6-b34a-24d59d2e30e2?wid=325&hei=325&qlt=80&fmt=pjpeg', in_stock=True
    )
    item11 = Item(
      name="Men's Statement Fleece Hoodie", category='Clothing, Shoes & Accessories', description='French terry pullover sweatshirt made of a midweight cotton-recycled polyester blend fabric. Long sleeves, an attached hood and the hand-warming front kangaroo pocket lend an additional layer of cozy comfort. The regular fit and at-hip length allow for cozy base layers. Tonal tie-dye print lends an attractive look.', price=44.95, image_url='https://target.scene7.com/is/image/Target/GUEST_f1260f84-7fd5-4f72-8392-eb5d28c5d46a?wid=325&hei=325&qlt=80&fmt=pjpeg', in_stock=True
    )
    item12 = Item(
      name="Women's Flex Ribbed Curvy Fit High-Rise 7/8 Leggings", category='Clothing, Shoes & Accessories', description='Flex Ribbed Curvy Fit High-Rise leggings in a solid hue help you power through all your fitness activities. Constructed with lightweight, moisture-wicking, quick-dry fabric made from recycled polyester and spandex. Designed in a skinny fit with full waistband elastic, side pocket and UPF 50+ sun protection for added convenience and comfort. 7/8 length lends on-trend style. Curvy fit.', price=39.95, image_url='https://target.scene7.com/is/image/Target/GUEST_d2c22634-e1ea-4c10-be70-4b79d55c4ef2?wid=325&hei=325&qlt=80&fmt=pjpeg', in_stock=True
    )
    item13 = Item(
      name='72" 5 Shelf Loring Ladder Bookshelf - Project 62', category='Furniture', description='With clean lines and plenty of shelf space, the Loring Five-Shelf Ladder Bookcase from Project 62™ is an elegant storage solution for a modern home. The understated metal frame contrasts with the wood-finish shelves to create a rustic feel. Taking up vertical space, this is an easy way to hold and display everything you need without cluttering up your room.', price=239.95, image_url='https://target.scene7.com/is/image/Target/GUEST_f0d47315-5f25-4c49-a858-b1ad987f87c8?wid=325&hei=325&qlt=80&fmt=pjpeg', in_stock=True
    )
    item14 = Item(
      name='Johannson Mid-Century Modern TV Stand for TVs up to 60" Brown', category='Furniture', description='Bring a functional update to your entertainment space with the Johannson Mid-Century Modern TV Stand from Project 62™. Featuring a rectangular silhouette, this dark brown wood-finish TV stand has a smooth tabletop that can accommodate TVs up to 60 inches. It also has multiple open shelves for keeping your gaming devices, remote controls and other media organized. These shelves with cord management cutouts and open backs are great for running cables through while maintaining a neat and tidy appearance.', price=339.95, image_url='https://target.scene7.com/is/image/Target/GUEST_59aa5967-8d02-4c05-a2e9-d8cf45694ad4?wid=325&hei=325&qlt=80&fmt=pjpeg', in_stock=True
    )
    item15 = Item(
      name='28" Emmond Mid-Century Modern Round Bistro Dining Table White', category='Furniture', description='Complete your modern-styled breakfast nook or coffee corner with the Emmond Mid-Century Round Bistro Table from Project 62™. This two-tone table brings together the clean, angular lines and simple shapes that are a hallmark of mid-century style. Complete the entire look by pairing it with complementing chairs and placing a small accent rug underneath.1962 was a big year. Modernist design hit its peak and moved into homes across the country. And in Minnesota, Target was born - with the revolutionary idea to celebrate design for all. Project 62 embodies this legacy with a collection of modern pieces made for everyday living.', price=339.95, image_url='https://target.scene7.com/is/image/Target/GUEST_3ab8ab7f-e07d-4b26-a6dd-5761f45baee0?wid=325&hei=325&qlt=80&fmt=pjpeg', in_stock=True
    )
    item16 = Item(
      name='Ferndale Metal Headboard Black', category='Furniture', description="Simple yet stylish, this Ferndale Metal Headboard from Threshold™ adds vintage-inspired flair to your bedroom decor. Made of metal in a matte black finish, this elegant headboard features an arched camel-back design with a spindle profile for a graceful, airy look in your bedroom. Simply attach it to the bed frame to finish off the look of your bedroom's decor with chic, welcoming style.", price=279.95, image_url='https://target.scene7.com/is/image/Target/GUEST_ad84fdbe-8db2-407c-a22b-26f4c6c0a7f0?wid=325&hei=325&qlt=80&fmt=pjpeg', in_stock=True
    )
    item17 = Item(
      name='Palermo Desk Daisy Webbing Brown', category='Furniture', description="The Palermo Desk from Opalhouse™ designed with Jungalow™ creates a perfect space to get work done, enjoy a good read or practice your artistic hobbies. Made from wood in a sleek brown finish, this rectangular desk has daisy webbing detailing on the side cabinet to add an attractive look to your home office. It features an ample tabletop for holding your necessities, while the drawer and side cabinet lend additional closed storage to organize some items out of sight. With a simple clean-lined silhouette, this desk complements nearly any design aesthetic or color palette.", price=379.95, image_url='https://target.scene7.com/is/image/Target/GUEST_5129db16-d91d-44ec-b9b0-10cdf8aae7e5?wid=325&hei=325&qlt=80&fmt=pjpeg', in_stock=True
    )
    item18 = Item(
      name='Esters Wood Arm Loveseat Husk Natural', category='Furniture', description="Whether you're relaxing alone or with a friend, you'll love the comfort of this Esters Wood Arm Loveseat from Project 62™. Designed with a natural wooden frame for a sleek foundation, this husk natural loveseat adds sleek style to your space. The solid color upholstery pairs with wooden frame for modern style that's perfect for any space in your home.", price=579.95, image_url='https://target.scene7.com/is/image/Target/GUEST_e86f6f2a-1148-4657-a012-04a402ff0a78?wid=325&hei=325&qlt=80&fmt=pjpeg', in_stock=True
    )
    item19 = Item(
      name='Arbon Wood Dowel Accent Chair with Cushion Arms', category='Furniture', description='Give your home a refreshed sleek, timeless and modern look with the Arbon Wood Dowel Accent Chair with Cushioned Arms from Threshold™ designed with Studio McGee. This beautiful wood-framed chair has a subtly classic look that complements any design theme in your home. The streamlined design of the sage colored cushions provides comfort and style. Plus, the neutral wood tones add warmth and elegance to any room. This beautiful accent chair is a great piece to add next to a couch or end table for completing a truly polished look. Whether it"s in a bedroom, living room or study, this elegant chair can elevate your home"s style anywhere.', price=379.95, image_url='https://target.scene7.com/is/image/Target/GUEST_7d0c9a36-5b09-4470-b53d-b3335790c962?wid=325&hei=325&qlt=80&fmt=pjpeg', in_stock=True
    )
    item20 = Item(
      name='32" Carson Horizontal Bookcase with Adjustable Shelves', category='Furniture', description='Create the perfect look for any room with the Carson Horizontal Bookcase from Threshold™. This horizontal bookcase offers multiple adjustable shelves you can arrange to suit your needs. Place in your home office, living room or bedroom to store books and DVDs. Decorate with a variety of knick knacks or even plants to add your own personal touch. This bookcase is made from sturdy hardware ensuring this addition to your home will be built to last.', price=279.95, image_url='https://target.scene7.com/is/image/Target/GUEST_7e332f93-5856-43bb-b054-2b601caa85b1?wid=325&hei=325&qlt=80&fmt=pjpeg', in_stock=True
    )
    item21 = Item(
      name='Cliff Haven Solid Wood with Woven Seat Counter Height Barstool', category='Furniture', description='Add a simple yet standout look to your kitchen or bar counter with this Cliff Haven Solid Wood with Woven Seat Counter Height Barstool from Threshold™ designed with Studio McGee. Set on a wooden frame with clean lines and a natural finish, this counter-height barstool features an arch-shape back and faux-leather woven seat in a rustic shade to complement the look. It stands at a fixed height of 24 inches to make it perfect for your space. Designed to mix with a wide variety of decor styles, this armless barstool also features a footrest for added convenience.', price=199.95, image_url='https://target.scene7.com/is/image/Target/GUEST_f4602e5b-b77e-4537-83bf-10c9951a1170?wid=325&hei=325&qlt=80&fmt=pjpeg', in_stock=True
    )
    item22 = Item(
      name='Loring Wood Writing Desk with Drawers', category='Furniture', description='Give your office charming and contemporary style with the Loring Writing Desk from Project 62™. The two plain-front drawers keep the look sleek and clean, making simplicity look so good. A large surface area means you can spread out your paperwork, making this desk the perfect blend of form and function.', price=229.95, image_url='https://target.scene7.com/is/image/Target/GUEST_a922477a-8770-462d-a9e5-71845637df18?wid=325&hei=325&qlt=80&fmt=pjpeg', in_stock=True
    )
    item23 = Item(
      name='Corinna Angle Leg Side Table Wood', category='Furniture', description='Wood and metal side table adds a classy touch to your space.', price=129.95, image_url='https://target.scene7.com/is/image/Target/GUEST_70f7370f-6e62-4bd1-a9b3-4b982eaacbc6?wid=325&hei=325&qlt=80&fmt=pjpeg', in_stock=True
    )
    item24 = Item(
      name='Tachuri Geometric Front Accent Table Brown', category='Furniture', description='Create a space that inspires creativity and speaks to your eclectic style with this Tachuri Geometric-Front Accent Table from Opalhouse™. The geometric embellishment across the front gives it captivating appeal, making it a stunning piece that no one will be able to miss when walking into the room. Place it next to your sofa styled with a decorative accent lamp and collected keepsakes that influence your exquisite taste in decor.', price=179.95, image_url='https://target.scene7.com/is/image/Target/GUEST_8332e21d-05bc-48b9-88d8-bff53b9c7f0b?wid=325&hei=325&qlt=80&fmt=pjpeg', in_stock=True
    )
    item25 = Item(
      name="De'Longhi 15 Bar Pump Espresso Machine", category='Kitchen & Dining', description='A compact and easy to use manual espresso and cappuccino maker would be a perfect fit for a small, cozy kitchen. To achieve a great extraction of espresso the machine is equipped with Italian 15 bar Pump. Also, with an integrated Premium Adjustable Frother, you can create Italian classic cappuccino with a dryer texture milk-foam or choose Hot Milk setting for your latte. 37 oz removable water tank, optional water filter, accommodates taller glasses, three-in-one filter holder, stainless steel boiler, stainless steel finish.', price=379.95, image_url='https://target.scene7.com/is/image/Target/GUEST_e760df84-a40d-413f-aa65-a21c0d36b26b?wid=325&hei=325&qlt=80&fmt=pjpeg', in_stock=True
    )
    item26 = Item(
      name="Mr. Coffee Café Barista, BVMC-ECMP1000", category='Kitchen & Dining', description="Brew coffeehouse-style drinks just the way you like them right at home. In one simple touch, Mr. Coffee Cafe Barista brews espresso coffee with a 15-bar pump system and automatically froths milk into cappuccino and latte selections. You don't need Barista know-how to create custom coffee drinks like your favorite coffeehouse. Simply pick a single shot or double shot filter, select your grounds, fill the milk reservoir and choose your brew. A recipe book is included to help you create impressive coffee drinks, from Espresso Martinis to Raspberry Cappuccinos to Chocó-Nutty Lattes. Mr. Coffee Cafe Barista will save you a stop at the coffeehouse on busy weekday mornings - saving you time and money, too.", price=359.95, image_url='https://target.scene7.com/is/image/Target/GUEST_73854e26-5c7f-4490-a505-ae3bb4410b9c?wid=325&hei=325&qlt=80&fmt=pjpeg', in_stock=True
    )
    item27 = Item(
      name="Nespresso Essenza Mini Black", category='Kitchen & Dining', description="Nespresso has delivered its most pure and sleek compact machine yet, without any compromise on taste! The Nespresso Essenza Mini machine offers 2 programmable cup sizes, is intuitive, easy to use, and creates perfect espresso coffee just the way you like it. This surprisingly small machine crafts great espresso in just a few minutes thanks to its high-pressure pump and fast heat-up system. Each machine includes a complimentary welcome set with a range of Nespresso capsules with unique aromatic profiles.", price=289.95, image_url='https://target.scene7.com/is/image/Target/GUEST_040d3b87-c992-49c0-9656-8989a1fd7bec?wid=325&hei=325&qlt=80&fmt=pjpeg', in_stock=True
    )
    item28 = Item(
      name="NutriChef 11 Piece Nonstick Ceramic Coating - Teal Blue", category='Kitchen & Dining', description="Anyone can be a sous chef with the help of the NutriChef 11 Piece Nonstick Elegant Lines Pattern Kitchen Cookware Set. This 11-piece non-stick kitchenware set features a stylish modern cookware design and elegant lines pattern to match any kitchen. The set includes a 1.7-quart saucepan pot with lid, 3.6-quart Dutch oven pot with lid, 2.1-quart cooking pot with lid, 11-inch large fry pan, 8-inch small fry pan, soup ladle, pasta fork, and spatula. With cool-touch and form-fitting handle grips, you can handle the pots and pans comfortably. The cookware set effectively distributes and retains heat so your food will be evenly cooked all around. The see-through tempered glass lids are great for keeping an eye on your food and the vent holes allow steam to escape. Cook up a storm on your gas, electric, ceramic, or induction counter cooktop with the NutriChef 11 Piece Nonstick Elegant Lines Pattern Kitchen Cookware Set.", price=249.95, image_url='https://target.scene7.com/is/image/Target/GUEST_0b27b85d-0ee0-4089-b51b-e33a4ced65e6?wid=325&hei=325&qlt=80&fmt=pjpeg', in_stock=True
    )
    item29 = Item(
      name='T-fal Ultimate Hard Anodized 16" x 13" Roaster', category='Kitchen & Dining', description='T-fal Ultimate Hard Anodized 16"x13" Roaster ensures reliable results when preparing meals for the whole family that everyone will love. This versatile Roaster makes anything from juicy turkeys and tender roasts to savory lasagnas and sweet cakes. The even heat base provides fast heating for even cooking results. Dishwasher and oven safe up to 400°F; limited lifetime warranty.', price=99.95, image_url='https://target.scene7.com/is/image/Target/GUEST_fba4e169-a886-4370-b3dd-69800c63d96a?wid=325&hei=325&qlt=80&fmt=pjpeg', in_stock=True
    )
    item30 = Item(
      name='GreenPan Bistro Noir Ceramic Nonstick Electric Grill & Griddle', category='Kitchen & Dining', description='Discover a new way to maximize your countertop cooking with the GreenPan Bistro Grill & Griddle. Reversible grill and griddle plates deliver plenty of options to customize your cooking experience. Fold it in half to get classic melts, paninis, burgers, and more! The plates adjust for maximum contact to ensure your food cooks evenly. It even lays flat to deliver double space or so you can use a grill and griddle at the same time.', price=199.95, image_url='https://target.scene7.com/is/image/Target/GUEST_94404862-dfce-48f7-99dc-06c999cc2868?wid=325&hei=325&qlt=80&fmt=pjpeg', in_stock=True
    )
    item31 = Item(
      name="16oz Stoneware 'Je T'aime' Mug", category='Kitchen & Dining', description="Enjoy your morning tea or coffee in sweet style with this 16-Ounce Stoneware Je T'aime Mug from Threshold™. This white stoneware mug features a gold script printed on the front that spells out Je t'aime, meaning I love you in French. Plus, a matching shiny gold heart appears just below the rim on the inside of the mug for a cute additional accent. Great for hot or cold beverages with its 16-ounce capacity and comfortable curved handle, you'll love starting your day with this microwave and dishwasher safe stoneware mug.", price=14.95, image_url='https://target.scene7.com/is/image/Target/GUEST_3ab6df04-c69a-444d-b1d3-3b33f9878c26?wid=325&hei=325&qlt=80&fmt=pjpeg', in_stock=True
    )
    item32 = Item(
      name="Dash Heart Mini Waffle Maker", category='Kitchen & Dining', description="Fall in love with fun, heart-shaped waffles with the Dash Heart Mini Waffle Maker! The 4 inch, non-stick surface makes delicious, heart-shaped treats in just minutes including waffles, hash-browns, and more. Easy to use, just plug the waffle maker in and you're ready to cook! The cute and compact size makes this Mini Maker easy to clean and store, and great for families with kids, gifting, or making a sweet treat for a special someone.", price=39.95, image_url='https://target.scene7.com/is/image/Target/GUEST_cd4f92aa-a277-426c-b0ba-1ee3c25b6607?wid=325&hei=325&qlt=80&fmt=pjpeg', in_stock=True
    )
    item33 = Item(
      name="12pc Glass Shoreham Double Old Fashion and Highball Glasses Set", category='Kitchen & Dining', description="The 12-Piece Glass Shoreham Double Old Fashioned and Highball Glasses Set from Threshold™ is great for everyday use or for special occasions where you'll be entertaining guests. This tastefully simple set blends well with any other glassware you may have at home. The set includes a total of 12 pieces. Six of the glasses have a 16-ounce capacity and six of them have a 13.3-ounce capacity, so you have the versatility of serving elaborate cocktails or just a glass of OJ in the morning. Thanks to the set's dishwasher-safe design, you know that cleanup will be an easy and stress-free process.", price=64.95, image_url='https://target.scene7.com/is/image/Target/GUEST_dd638d94-8d5d-4df9-bdce-afb34179fa7e?wid=325&hei=325&qlt=80&fmt=pjpeg', in_stock=True
    )
    item34 = Item(
      name="PowerXL Vortex Pro Air Fryer 4qt", category='Kitchen & Dining', description="Powered by Vortex Rapid Air Technology, the 4-quart PowerXL Vortex Air Fryer delivers deliciously crispy results while replacing 7 appliances in one compact, space-saving design. The air fryer allows you to cook fast, easy meals without having to preheat traditional oven appliances. Vortex Rapid Air Circulation generates powerful air flow to reach high temperatures and cook around all sides of your food for even doneness throughout and a hot, golden-fried finish. A full menu of 10 intuitive presets allows you to make pizzas, bake cookies, broil meat, fish, and vegetables, dehydrate fruit snacks and veggie chips, and even revive last night's leftover pizza with a crispy finish. Just press one of the buttons on the easy-to-read LED digital touchscreen or program your own time and temperature.", price=109.95, image_url='https://target.scene7.com/is/image/Target/GUEST_3af0dcaa-a013-431c-b2d5-ca701e4b8f96?wid=325&hei=325&qlt=80&fmt=pjpeg', in_stock=True
    )
    item35 = Item(
      name="Oster Easy-to-Use 5 Speed Blender", category='Kitchen & Dining', description="Blend effortlessly with the Oster® Easy-to-Use Blender. This Oster blender features a modern design and intuitive, easy-to-use push-button controls to help you make your favorite smoothies, snacks, frozen drinks, salsas, and more. Experience 5-speed versatility including Blend, Mix, Chop, Ice Crush, and Pulse at the touch of a button.", price=79.95, image_url='https://target.scene7.com/is/image/Target/GUEST_e6f9c684-7fae-47f1-be91-cb56e431b49e?wid=325&hei=325&qlt=80&fmt=pjpeg', in_stock=True
    )
    item36 = Item(
      name="SodaStream 60L CO2 Spare Carbonator", category='Kitchen & Dining', description="Get yourself a nice tall glass of bubbly water whenever you like, with the SodaStream carbonator. Carbonate up to 60L of water with this CO2 tank, which you can return to save on your next one. It contains 14.5oz of CO2 for you to fizz up your beverage and enjoy a nice, bubbly drink.", price=49.95, image_url='https://target.scene7.com/is/image/Target/GUEST_78db5676-9ee5-492d-a560-bc7d8da2d36b?wid=325&hei=325&qlt=80&fmt=pjpeg', in_stock=True
    )

    items = [item1, item2, item3, item4, item5, item6, item7, item8, item9, item10, item11, item12, item13, item14, item15, item16, item17, item18, item19, item20, item21, item22, item23, item24, item25, item26, item27, item28, item29, item30, item31, item32, item33, item34, item35, item36]
    [db.session.add(item) for item in items]
    db.session.commit()


# Uses a raw SQL query to TRUNCATE or DELETE the items table. SQLAlchemy doesn't
# have a built in function to do this. With postgres in production TRUNCATE
# removes all the data from the table, and RESET IDENTITY resets the auto
# incrementing primary key, CASCADE deletes any dependent entities.  With
# sqlite3 in development you need to instead use DELETE to remove all data and
# it will reset the primary keys for you as well.
def undo_items():
    if environment == "production":
        db.session.execute(f"TRUNCATE table {SCHEMA}.items RESTART IDENTITY CASCADE;")
    else:
        db.session.execute("DELETE FROM items")

    db.session.commit()
